version: 2

models:
  - name: dim_dates
    description: >
      Calendar date dimension spanning 2000-01-01 to 2030-12-31. One row per day.
      Provides calendar, seasonal, and business calendar attributes for time-based analysis.
      The surrogate key (date_sk) is an integer in YYYYMMDD format for fast joins.
    columns:
      - name: date_sk
        description: Integer surrogate key in YYYYMMDD format (e.g., 20230715 for July 15 2023)
        tests:
          - not_null
          - unique

      - name: full_date
        description: Calendar date — join column for fact_movies.release_date
        tests:
          - not_null
          - unique

      - name: calendar_year
        description: Four-digit year

      - name: release_season
        description: "Seasonal classification: SUMMER | HOLIDAY | WINTER | SPRING | FALL"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['SUMMER', 'HOLIDAY', 'WINTER', 'SPRING', 'FALL']

  - name: dim_genres
    description: >
      Genre dimension with surrogate key, business enrichment (genre_group,
      is_blockbuster_genre), and full lineage to silver_genres.
    columns:
      - name: genre_sk
        description: Surrogate key generated by dbt_utils.generate_surrogate_key
        tests:
          - not_null
          - unique

      - name: genre_id
        description: TMDb natural genre ID — preserved for source system tracing
        tests:
          - not_null
          - unique

      - name: genre_name
        description: UPPER CASE genre display name
        tests:
          - not_null
          - unique

      - name: genre_group
        description: "Business genre grouping: HIGH_OCTANE | NARRATIVE | LIGHT | NICHE | ARTS | OTHER"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['HIGH_OCTANE', 'NARRATIVE', 'LIGHT', 'NICHE', 'ARTS', 'OTHER']

  - name: dim_production_companies
    description: >
      Production company dimension with studio tier classification and geographic region.
    columns:
      - name: company_sk
        description: Surrogate key
        tests:
          - not_null
          - unique

      - name: company_id
        description: TMDb natural company ID
        tests:
          - not_null
          - unique

      - name: studio_tier
        description: "Classification: MAJOR_STUDIO | MINI_MAJOR | INDIE | UNKNOWN"
        tests:
          - accepted_values:
              arguments:
                values: ['MAJOR_STUDIO', 'MINI_MAJOR', 'INDIE', 'UNKNOWN']

  - name: fact_movies
    description: >
      Central fact table — one row per released movie. Contains all quantitative
      measures and foreign keys to all dimension tables. Grain: one row per movie
      (primary genre only). Non-primary genres accessible via silver_movie_genres.
    columns:
      - name: movie_sk
        description: Surrogate key for the fact row
        tests:
          - not_null
          - unique

      - name: movie_id
        description: TMDb natural movie ID
        tests:
          - not_null
          - unique

      - name: vote_average
        description: TMDb community average rating (0-10)
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 10
                row_condition: "vote_average is not null"

      - name: profitability_flag
        description: "Derived: PROFITABLE | BREAK_EVEN | LOSS | UNKNOWN"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['PROFITABLE', 'BREAK_EVEN', 'LOSS', 'UNKNOWN']

  - name: kpi_genre_performance
    description: >
      Pre-aggregated genre performance KPI mart. One row per genre.
      Used by dashboards showing "Genre Revenue Comparison" and "ROI by Genre".
    columns:
      - name: genre_name
        description: Genre display name
        tests:
          - not_null
          - unique

      - name: avg_roi_pct
        description: Average return on investment across financially complete movies

      - name: roi_rank
        description: Genre ranked by average ROI (1 = highest ROI genre)
        tests:
          - not_null

  - name: kpi_yearly_trends
    description: >
      Year-over-year movie industry trends from 1980 to present.
      One row per release year. Includes YoY delta columns for trend analysis.
    columns:
      - name: release_year
        description: Four-digit release year
        tests:
          - not_null
          - unique

  - name: kpi_top_movies
    description: >
      Top movies with multi-dimensional rankings — revenue, ROI, rating, popularity.
      One row per movie with vote_count >= 100. Joins genres and companies for labels.
    columns:
      - name: movie_sk
        description: Surrogate key — matches fact_movies
        tests:
          - not_null
          - unique

      - name: revenue_rank_all_time
        description: All-time revenue rank (1 = highest-grossing movie ever)
