version: 2

# =============================================================================
# TEACHING NOTE -- Gold Layer Schema Tests
# =============================================================================
# Gold layer = Star Schema (dims + fact). KPI models moved to models/marts/.
#
# Tests in this file focus on:
#   1. Star schema integrity  -- SK uniqueness, FK relationships to dims
#   2. Dimension completeness -- accepted_values, no impossible data
#   3. Fact table quality     -- metric ranges, profitability flag correctness
#   4. dbt_expectations       -- statistical and cross-column validations
#
# IMPORTANT: kpi_genre_performance, kpi_yearly_trends, kpi_top_movies tests
# have been MOVED to models/marts/schema.yml (those models now live in marts/).
# =============================================================================

models:

  # -- dim_dates --------------------------------------------------------------
  - name: dim_dates
    description: >
      Calendar date dimension spanning 2000-01-01 to 2030-12-31. One row per day.
      Provides calendar, seasonal, and business calendar attributes for time-based analysis.
      Surrogate key (date_sk) is an integer YYYYMMDD format for fast, readable joins.
      Generated by dbt_utils.date_spine() macro. Used as FK in fact_movies.

    tests:
      # TEACHING: Table-level test -- validate row count matches expected date range
      # 2000-01-01 to 2030-12-31 = approximately 11,323 days
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 10000
          max_value: 15000

    columns:
      - name: date_sk
        description: Integer surrogate key in YYYYMMDD format (e.g., 20230715 for July 15 2023)
        tests:
          - not_null
          - unique

      - name: full_date
        description: Calendar date -- join column for fact_movies.release_date
        tests:
          - not_null
          - unique

      - name: calendar_year
        description: Four-digit calendar year
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 2000
              max_value: 2030

      - name: calendar_month
        description: Month number (1-12)
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 12

      - name: release_season
        description: "Seasonal classification: SUMMER | HOLIDAY | WINTER | SPRING | FALL"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['SUMMER', 'HOLIDAY', 'WINTER', 'SPRING', 'FALL']

  # -- dim_genres ------------------------------------------------------------
  - name: dim_genres
    description: >
      Genre dimension with surrogate key, business enrichment (genre_group,
      is_blockbuster_genre), and full lineage to silver_genres. ~19 TMDb genres.
      SCD2 history tracked by snapshots/snap_dim_genres.sql.

    tests:
      # TMDb has ~19 stable genres -- validate this assumption
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 10
          max_value: 30

    columns:
      - name: genre_sk
        description: Surrogate key generated by dbt_utils.generate_surrogate_key(['genre_id'])
        tests:
          - not_null
          - unique

      - name: genre_id
        description: TMDb natural genre ID -- preserved for source system tracing
        tests:
          - not_null
          - unique

      - name: genre_name
        description: UPPER CASE genre display name
        tests:
          - not_null
          - unique

      - name: genre_group
        description: "Business genre grouping: HIGH_OCTANE | NARRATIVE | LIGHT | NICHE | ARTS | OTHER"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['HIGH_OCTANE', 'NARRATIVE', 'LIGHT', 'NICHE', 'ARTS', 'OTHER']

  # -- dim_production_companies -----------------------------------------------
  - name: dim_production_companies
    description: >
      Production company dimension with studio tier classification and geographic region.
      Unique per company_id. Companies appear in multiple movies (one-to-many relationship).

    columns:
      - name: company_sk
        description: Surrogate key
        tests:
          - not_null
          - unique

      - name: company_id
        description: TMDb natural company ID
        tests:
          - not_null
          - unique

      - name: studio_tier
        description: "Classification: MAJOR_STUDIO | MINI_MAJOR | INDIE | UNKNOWN"
        tests:
          - accepted_values:
              arguments:
                values: ['MAJOR_STUDIO', 'MINI_MAJOR', 'INDIE', 'UNKNOWN']

      - name: region
        description: "Geographic region: NORTH_AMERICA | EUROPE | ASIA_PACIFIC | OTHER"
        tests:
          - accepted_values:
              arguments:
                values: ['NORTH_AMERICA', 'EUROPE', 'ASIA_PACIFIC', 'OTHER']

  # -- fact_movies ------------------------------------------------------------
  - name: fact_movies
    description: >
      Central fact table -- one row per released movie (primary genre only).
      Contains all quantitative measures and foreign keys to all dimension tables.
      Non-primary genres accessible via silver_movie_genres bridge table.
      SCD2 history of financial/quality changes tracked by snapshots/snap_silver_movies.sql.

    tests:
      # Should have at least a few movies
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 1
          max_value: 1000000

    columns:
      - name: movie_sk
        description: Surrogate key for the fact row
        tests:
          - not_null
          - unique

      - name: movie_id
        description: TMDb natural movie ID
        tests:
          - not_null
          - unique

      - name: vote_average
        description: TMDb community average rating (0-10)
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 10
              row_condition: "vote_average is not null"

      - name: vote_count
        description: Number of TMDb votes -- must be non-negative
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 10000000
              row_condition: "vote_count is not null"

      - name: budget_usd
        description: Production budget in USD -- NULL means unreported (TMDb uses 0 for unknown)
        tests:
          # Budget should never be negative if reported
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1000000000
              row_condition: "budget_usd is not null"

      - name: revenue_usd
        description: Worldwide box office revenue in USD -- NULL means unreported
        tests:
          # Revenue must be non-negative
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 5000000000
              row_condition: "revenue_usd is not null"

      - name: runtime_minutes
        description: Film runtime in minutes
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 600
              row_condition: "runtime_minutes is not null"

      - name: release_year
        description: Calendar year of theatrical release
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1888
              max_value: 2030
              row_condition: "release_year is not null"

      - name: profitability_flag
        description: "Derived: PROFITABLE | BREAK_EVEN | LOSS | UNKNOWN"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['PROFITABLE', 'BREAK_EVEN', 'LOSS', 'UNKNOWN']

      - name: date_sk
        description: FK to dim_dates.date_sk -- YYYYMMDD integer format
        tests:
          # TEACHING: This relationship test ensures referential integrity
          # Every release date in fact_movies must exist in dim_dates
          - relationships:
              arguments:
                to: ref('dim_dates')
                field: date_sk
